### ISSUE TITLE
Bring documentation up to speed

### ISSUE THREAD

**Issue by Tugark** [gipfeli-io/documentation#16]
- [x] Add column for review information to requirements and non functional requirements (lukas)
- [x] Update domain model (lukas)
- [x] Update Arch Overview layer spec (use plantuml) (sabrina)
- [x] Api Arch check if complete / update if needed (lukas)
- [x] Frontend Arch check if complete / update if needed (sabrina)
- [x] Add page for Schlussbericht and persönliches Fazit (sabrina)
- [x] Infrastructure Basics add Mail Server info (lukas)
- [x] Extend Setup, link setup in technical docs intro page, check readmes
- [x] Add links to sonar, sentry etc in intro doc (sabrina)
- [x] Check Deployment information (frontend, backend, documentation) (lukas)
- [x] Remove basics folder in design (sabrina)
- [x] Check Uses Cases , remove UC11 (sabrina/lukas)
- [x] Move offline support info to frontend architecture (sabrina)

# Review

- [x] Documentation is written
- [x] Documentation is reviewed
- [x] Build is successful
- [x] Deployment to production works

**Comment by Saela** [comment]
@Saela I moved this to the ticket itself as TODO items :)

**Comment by Tugark** [comment]
@Saela I added two missing development meeting notes in https://github.com/gipfeli-io/documentation/commit/6dc0ce74fa0a09e56db4c519a8bd962b2526163d as well.
